IEEESFIT1/OpenOctober

SoftwareDev/C/InfixToPostfix.c, SoftwareDev/C/Postfix_Eval.c
1. Added Postfix Expression evaluation program in C
2. Resoved an error in InfixToPostfix.c at line 86, shown by Code Inspector
3. Optimized Postfix_Eval.c
=> Added Postfix Expression Evaluation Program in C

IoT/Arduino/Blinking_External_LED.ino
In this program, we use an Arduino Uno, a LED and a simple 1k resistor
The connection is made at the Arduino Digital PWM port 8
Fixes #23
=> Program to use Arduino to cause an LED to Blink continually

IoT/Arduino/Fade_LED.ino
My first contribution to OpenOctober
=> Program to use Arduino to cause an LED to fade

SoftwareDev/Python/bin_search.py
This is a simple Python program for the binary search algorithm
The input array and the element to be searched is taken from the user
=> Binary Search Algorithm in Python

Miscellaneouos/Python/Socket Programming/Client/TCP_Client.py, Miscellaneouos/Python/Socket Programming/Client/demo.txt, Miscellaneouos/Python/Socket Programming/Server/TCP_Server.py, Miscellaneouos/Python/Socket Programming/Server/demo2.txt
The file has two folders: a server and a client. Both need to be run simultaneously on different instances of IDLE and can be executed.
The program also allows you to transfer files and read its content
=> Socket Programming update

SoftwareDev/C/Bresenham_Algo.c, SoftwareDev/C/DDA.c, SoftwareDev/C/Midpoint_Ellipse.c
This pull request Fixes issue #75  
Following Programs are Added :
- Digital Differential Analyzer (DDA) Algorithm 
- Bresenham's Line Drawing Algorithm 
- Midpoint Ellipse Generating Algorithm
=> Software Dev: C Programs to implement CG Algorithms : Fixes issue #75

SoftwareDev/C/binery tree.c
This is the commit as per issue #27 
Data structure and algorithm to implement Binary trees and its traversal
=> added binary tree with traversal algo

SoftwareDev/C++/periodic_table/periodic_table.cpp
=> Add Periodic Table Implementation

EthicalHacking/Python/Cryptography/Client/Client.py, EthicalHacking/Python/Cryptography/Client/test2.txt, EthicalHacking/Python/Cryptography/Server/Server.py, EthicalHacking/Python/Cryptography/Server/test.txt
This is GUI based Cryptography application that using OneTimePad for encryption of files or text messages sent between two clients connected via a Socket connection. Each user can transfer files and Texts easily giving just a key for encryption. If during the transfer the message is siphoned it will be in an encrypted form and will not be easy to decipher
=> Cryptography with Py

SoftwareDev/C++/IEEEXtreme 14.0/Crafting_Wooden_Tables.cpp, SoftwareDev/C++/IEEEXtreme 14.0/Hotel_Wiring.cpp, SoftwareDev/C++/IEEEXtreme 14.0/Mosaic_Decoration_1.cpp, SoftwareDev/C++/IEEEXtreme 14.0/Mosaic_Decoration_2.cpp, SoftwareDev/C++/IEEEXtreme 14.0/Non_Overlapping_Palindromes.cpp, SoftwareDev/C++/IEEEXtreme 14.0/Rotational_Lights.cpp
=> IEEE Xtreme14.0 Cpp Codes

ML_AI/Python/NumPy/NumPy_Tutorial.ipynb
PR to issue #126 
@csendranshi please let me know if any changes are required.
=> Added tutorial of NumPy

ML_AI/Python/PyTorch/Denoising_Autoencoder_MNIST.ipynb
Fixes issue #131 
@orvil1026 @csendranshi 
Please assign the other issues of mine too, thanks:)
=> Added Denoising Autoencoder

SoftwareDev/C++/graphtheory/Bellman_Ford_Algorithm.cpp
=> Add Bellman Ford Algo

SoftwareDev/C++/segment_tree.cpp
=> Adding segment tree algo CP

SoftwareDev/C/Inserting_node_linkedlist.c, SoftwareDev/C/Length_of_linkedlist.c
Fixes #152 
@csendranshi @orvil1026
=> Adding examples on linkedlist

ML_AI/Python/PyTorch/Resnet_models.py
Fixes issue #142 
@clare0901 @csendranshi @orvil1026
=> Added Resnet Model in PyTorch

ML_AI/Python/SVM/SVM_example.ipynb
Fixes issue #139 
@csendranshi @orvil1026 please review the code:)
=> Added SVM example

SoftwareDev/C/Convert_tree_mirror_image.c, SoftwareDev/C/Two_trees_identical_test.c
=> Added model problems on trees

ML_AI/Python/Pandas/Pandas_Tutorial.ipynb
=> Added pandas example code

ML_AI/Python/PyTorch/PyTorch_tensor_tutorial.ipynb
=> Added tensor tutorial

SoftwareDev/C++/binary_search_stl.cpp
=> Binary Search STL

ML_AI/Python/PyTorch/PyTorch_Autograd_tutorial.ipynb
=> Added Autograd example codes

ML_AI/Python/PyTorch/RNN_PyTorch_MNIST.ipynb
=> Added RNN example

IoT/Arduino/Press_Button.ino
Fixes issue #208 
Pls review @csendranshi @clare0901 @orvil1026
=> Program to use a push button to control a LED

IoT/Arduino/Photoresistor.ino
=> Program to use a photoresistor to turn on a LED

ML_AI/Python/PyTorch/Convnet_PyTorch.ipynb
=> Added Convnet example

SoftwareDev/C++/Merge_Sort.cpp
=> C++ Merge Sort

ML_AI/Python/PyTorch/Dogbreed_PyTorch.ipynb
=> Added Dog breed classifier

SoftwareDev/C++/Merge_Sort_3_Parition.cpp
=> Merge Sort using 3 Partition method

SoftwareDev/C/Boundary_Fill.c, SoftwareDev/C/Flood_Fill.c, SoftwareDev/C/HELLO_WO.CPP, SoftwareDev/C/SLPF.c
This PR resolves issue #155 .
Following Programs are added :
- Boundary Fill Algorithm
- Flood Fill Algorithm
- Scan Line Polygon Fill Algorithm
Also, HELLO_WO.CPP under Software Dev/C is deleted to Sync with OpenOctober base:master and to avoid conflicts.
=> Software Dev: Implementation CG (Area Filling) Algorithms Resolves issue #155

ML_AI/Python/PyTorch/PyTorch_starter.ipynb
=> Added Intro to Pytorch

ML_AI/Python/RandomForest/random_forest_classifier.py
=> Added random forest classifier

SoftwareDev/C++/Floyds_Algorithm.cpp
=> Add Floyd's Cycle detection algo

SoftwareDev/C++/Kadanes_Algorithm.cpp
=> Add Kadane's Algorithm

ML_AI/Python/PyTorch/Regularization_PyTorch.ipynb
Fixes issue #259 
@clare0901 @csendranshi
=> Added regularization notebook

ML_AI/Python/Keras/CNN_Keras_tutorial.ipynb
Fixes issue #262 
@clare0901 @csendranshi
=> Added cnn keras

SoftwareDev/C++/Sieve_of_Eratosthenes.cpp
=> Add Sieve of Eratosthenes Cpp

SoftwareDev/C/Count_occurence_linkedlists.c
Fixes issue #282 
@csendranshi @clare0901
=> Added occurence linkedlist problem

ML_AI/Python/PyTorch/Bayesian_nn.ipynb
Fixes issue #284 
@csendranshi @clare0901
=> Added Bayesian NN

SoftwareDev/C++/KMP_Algorithm.cpp
=> Add KMP algorithm

SoftwareDev/C/Sum_of_treenodes.c
=> Create Sum_of_treenodes in C

SoftwareDev/C++/Hashing_Algorithm.cpp
=> Add Hashing Algorithm for strings

ML_AI/Python/PyTorch/VAE.ipynb
=> Added VAE example

SoftwareDev/C++/Naive_String_Searching.cpp
=> Add Naive String Searching Algo

SoftwareDev/Java/test.java
=> Add test.java for creating Non-Blocking Socket

SoftwareDev/C++/Boyer_Moore_Algo.cpp
=> Add Boyer Moores Algo

ML_AI/Python/Multi-label classification/multilabel_classification.py
Fixes issue #317 
@csendranshi @clare0901
=> Added multi label classification example

ML_AI/Python/PyTorch/Space_stretching.ipynb
Fixes issue #314 
@csendranshi @clare0901
=> Added space stretching example

SoftwareDev/C++/Multiple_Inheritance.cpp
=> Program to illustrate Multiple inheritance in cpp

SoftwareDev/Java/FTPLogin.java
=> Add FTPLogin.java

SoftwareDev/C++/Tree_Traversals.cpp
=> Add Tree Traversal Program

SoftwareDev/C/Ptriangle.c
=> Add Pascal triangle in C

SoftwareDev/C++/Knapsack_Greedy.cpp
=> Greedy approach to Knapsack problem

SoftwareDev/C++/Vectors_STL.cpp
=> Add implementation of STL containers using Vectors

SoftwareDev/C++/NearestNeighbour.cpp
=> Add Nearest Neighbour Algorithm

ML_AI/Python/PyTorch/vgg16_model.py
=> Added VGG16

SoftwareDev/C++/Knapsack_DP.cpp
=> Implementation of knapsack problem using DP (C++)

SoftwareDev/C/Alt_merge_linkedlist.c
Fixes #357 
Have verified the code, please review @csendranshi
=> Alternate merge of 2 linkedlists

SoftwareDev/Java/MorrisTraversal.java
=> Add Inorder Traversal of Binary Tree using Morris Traversal

SoftwareDev/C++/Unordered_sets.cpp
=> Implementing unordered_sets in C++

SoftwareDev/C++/Johnsons_Algorithm.cpp
=> Implement Johnson's Algo

ML_AI/Python/PyTorch/Enet_PyTorch.py
=> Added Enet in PyTorch

SoftwareDev/Python/RabinKarp.py
=> Rabin Karp Python Implementation

SoftwareDev/C++/Z_Algorithm.cpp
=> Z's Algorithm C++

ML_AI/Python/PyTorch/MNIST_PyTorch.ipynb
=> Added MNIST pytorch cnn

SoftwareDev/C++/KruskalAlgo.cpp
=> Add Kruskal Algorithm

SoftwareDev/C++/CRT.cpp
=> Add Chinese Remainder Theorem

SoftwareDev/C++/Rho_Algorithm.cpp
=> Rho's algo

ML_AI/Python/PyTorch/Violence_detection/ConvLSTMCell.py, ML_AI/Python/PyTorch/Violence_detection/main-run-vr.py
=> Added violence detection

SoftwareDev/C/DutchFlag.c
=> Add Dutch Flag Problem in C

DataScience/Jupyter Notebook/Cross Validation/Cross-Validation_Grid_Search_with_Random_Forest.ipynb, DataScience/Jupyter Notebook/Cross Validation/Cross-Validation_and_Feature_Engineering.ipynb
=> Cross Validation

SoftwareDev/C++/graham_scan.cpp
=> Graham Scan Algo

DataScience/Jupyter Notebook/Data_Exploration_and_Cleaning.ipynb
=> Data exploration and cleaning

SoftwareDev/C/MeanMedian.c
=> Add Mean and Median Problem

SoftwareDev/C++/convex hull.cpp
=> convex hull implementation

SoftwareDev/Java/PythagoreanTriplet.java
=> Add PythagoranTriplet.java

SoftwareDev/C++/Suffix_Automata.cpp
=> Suffix Automata Implementation

SoftwareDev/C++/Dinics_Algo.cpp
=> Dinic's Algo

ML_AI/Python/PyTorch/pspnet.py
=> Added PSPnet

SoftwareDev/C++/Tries.cpp
=> Tries Implementation cpp

SoftwareDev/Java/CollatzSequence.java
=> Add CollatzSequence.java

SoftwareDev/Java/MagicNumber.java
=> Add MagicNumber.java

SoftwareDev/C++/Catalan_Numbers.cpp, SoftwareDev/C++/Modular_Inverse.cpp
=> Catalan Numbers Cpp

SoftwareDev/C++/Heavy_Light_Decomp.cpp
=> Heavy light decomp

.github/workflows/greetings.yml
ISSUE:  #86 
Removed pull_request as it was failing on this and also not supported by github for now.
Additionally added link to see contributing guidelines.
=> removed action on PR and added contribution link

SoftwareDev/Python/karatsubaAlgo.py
=> Add KaratsubaAlgo.py

SoftwareDev/C++/Totient_function.cpp
=> Totient Function C++

SoftwareDev/C++/Modular_Inverse.cpp
=> Mod Inverse Implementation cpp

SoftwareDev/Python/pigeonholeSort.py
=> Add pigeonholeSort.py

SoftwareDev/C++/Miller_Rabin.cpp
=> Miller Rabin Cpp

SoftwareDev/C++/Segmented_Sieve.cpp
=> Segmented Sieve Cpp

SoftwareDev/C++/Linear-Diophantine.cpp
=> Implemented Linear Diophantine equations in Cpp

SoftwareDev/C++/Inversions_using_bit.cpp
=> Inversions using Binary Indexed Tree (BIT)

ML_AI/Python/K-Means_cluster/k_means_clust.py
=> Added kmeans

SoftwareDev/C++/bigmod.cpp
=> Add Bigmod.cpp

SoftwareDev/C++/BucketSort.cpp
=> Add BucketSort.cpp

SoftwareDev/C++/Sparse_Table.cpp
=> Sparse Table Implementation Cpp

SoftwareDev/C++/PancakeSort.cpp
=> Add PancakeSort.cpp

SoftwareDev/C++/evilNum.cpp
=> Add evilNum.cpp

SoftwareDev/Java/Automorphic.java
=> Add Automorphic.java

SoftwareDev/C++/Disjoint_union_set.cpp
=> DSU Implemention C++

SoftwareDev/C++/Fenwick_tree.cpp
=> Fenwick Tree Implementation C++

SoftwareDev/C++/KD_Tree.cpp
=> KD Tree Implementation Cpp

ML_AI/Python/Polynomial_regression/polymonial_regression.py
=> Added polynomial regression

ML_AI/Python/Gradient_descent/gradient_descent.py
=> Added grad descent

SoftwareDev/Java/Maze.java
=> Add Maze.java

SoftwareDev/Java/CheckForArmstrongNo.java
=> Add CheckForArmstrongNo.java

SoftwareDev/C++/LCA_using_RMQ.cpp
=> LCA Implementation using RMQ Cpp

SoftwareDev/C++/Mo_Algo.cpp
=> Implementation of Mo's Algo using Cpp

SoftwareDev/Java/powerset.java
=> Add powerSet.java

SoftwareDev/Java/RotateClockwise.java
=> Add RotateClockwise.java

SoftwareDev/C++/Line_intersection_algo.cpp
=> Line Intersection Algo

Algorithms/linear_search.c, Data Structures/Tree/TREE.C
Added linear search to algo and tree in ds
=>  Added liner search
